2025-03-09 02:00:59,794 - ERROR - pulnest_app - get_user_by_phone - Line 46 - Error fetching user by phone 992929929292: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5433 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-03-09 02:02:47,657 - WARNING - pulnest_app - get_user_by_phone - Line 43 - No user found by phone: 992929929292
2025-03-09 02:02:47,659 - WARNING - pulnest_app - get_user_by_email - Line 29 - No user found by email: mehrona.nm@gmail.com
2025-03-09 02:02:47,893 - INFO - pulnest_app - create_user - Line 14 - User created successfully with ID: 1
2025-03-09 02:02:56,946 - INFO - pulnest_app - get_user_by_email - Line 27 - User found by email: mehrona.nm@gmail.com
2025-03-09 02:02:56,956 - INFO - pulnest_app - get_user_by_email - Line 27 - User found by email: mehrona.nm@gmail.com
2025-03-09 02:02:56,960 - INFO - pulnest_app - save_verification_code - Line 94 - Verification code saved for email: mehrona.nm@gmail.com
2025-03-09 02:03:26,098 - INFO - pulnest_app - get_verification_code - Line 106 - Verification code found for email: mehrona.nm@gmail.com
2025-03-09 02:03:26,110 - INFO - pulnest_app - verify_user - Line 70 - User mehrona.nm@gmail.com verified successfully.
2025-03-09 02:03:26,113 - INFO - pulnest_app - get_user_by_email - Line 27 - User found by email: mehrona.nm@gmail.com
2025-03-09 02:03:59,204 - INFO - pulnest_app - get_verification_code - Line 106 - Verification code found for email: mehrona.nm@gmail.com
2025-03-09 02:03:59,204 - INFO - pulnest_app - verify_user - Line 70 - User mehrona.nm@gmail.com verified successfully.
2025-03-09 02:03:59,219 - INFO - pulnest_app - get_user_by_email - Line 27 - User found by email: mehrona.nm@gmail.com
2025-03-09 02:04:06,492 - INFO - pulnest_app - get_verification_code - Line 106 - Verification code found for email: mehrona.nm@gmail.com
2025-03-09 02:04:06,496 - INFO - pulnest_app - verify_user - Line 70 - User mehrona.nm@gmail.com verified successfully.
2025-03-09 02:04:06,497 - INFO - pulnest_app - get_user_by_email - Line 27 - User found by email: mehrona.nm@gmail.com
2025-03-09 02:04:06,512 - INFO - pulnest_app - create_wallet - Line 17 - Wallet created for user 1.
2025-03-09 02:04:06,515 - INFO - pulnest_app - delete_verification_code - Line 119 - Verification code deleted for email: mehrona.nm@gmail.com
2025-03-09 02:04:11,114 - WARNING - pulnest_app - get_user_by_phone - Line 43 - No user found by phone: 992929929293
2025-03-09 02:04:18,212 - INFO - pulnest_app - get_user_by_phone - Line 41 - User found by phone: 992929929292
2025-03-09 02:04:31,162 - INFO - pulnest_app - get_wallet_balance - Line 19 - Get users wallet balance. Request user: 1
2025-03-09 02:04:31,165 - INFO - pulnest_app - get_wallet_by_user_id - Line 33 - Wallet found for user 1.
2025-03-09 02:04:31,167 - INFO - pulnest_app - get_wallet_balance - Line 45 - Wallet balance retrieved for user 1.
2025-03-09 03:13:43,963 - INFO - pulnest_app - get_wallet_endpoint - Line 38 - Get wallet balance for user 1.
2025-03-09 03:13:43,973 - INFO - pulnest_app - get_wallet_by_user_id - Line 33 - Wallet found for user 1.
2025-03-09 03:13:43,976 - INFO - pulnest_app - get_wallet_balance - Line 56 - Wallet balance retrieved for user 1.
2025-03-09 03:13:43,976 - ERROR - pulnest_app - get_wallet_endpoint - Line 50 - Error retrieving wallet balance for user 1: 404: Wallet not found
2025-03-09 03:13:49,980 - INFO - pulnest_app - get_user_by_phone - Line 41 - User found by phone: 992929929292
2025-03-09 03:14:03,494 - INFO - pulnest_app - get_wallet_endpoint - Line 38 - Get wallet balance for user 1.
2025-03-09 03:14:03,496 - INFO - pulnest_app - get_wallet_by_user_id - Line 33 - Wallet found for user 1.
2025-03-09 03:14:03,496 - INFO - pulnest_app - get_wallet_balance - Line 56 - Wallet balance retrieved for user 1.
2025-03-09 03:14:03,500 - ERROR - pulnest_app - get_wallet_endpoint - Line 50 - Error retrieving wallet balance for user 1: 404: Wallet not found
2025-03-09 03:16:09,018 - INFO - pulnest_app - get_user_by_phone - Line 41 - User found by phone: 992929929292
2025-03-09 03:16:24,356 - INFO - pulnest_app - get_wallet_endpoint - Line 38 - Get wallet balance for user 1.
2025-03-09 03:16:24,364 - INFO - pulnest_app - get_wallet_by_user_id - Line 33 - Wallet found for user 1.
2025-03-09 03:16:24,366 - INFO - pulnest_app - get_wallet_balance - Line 56 - Wallet balance retrieved for user 1.
2025-03-09 03:16:24,366 - ERROR - pulnest_app - get_wallet_endpoint - Line 50 - Error retrieving wallet balance for user 1: 404: Wallet not found
2025-03-09 03:17:12,100 - INFO - pulnest_app - get_user_by_phone - Line 41 - User found by phone: 992929929292
2025-03-09 03:17:12,100 - INFO - pulnest_app - get_user_by_email - Line 27 - User found by email: mehrona.nm@gmail.com
2025-03-09 03:19:09,634 - INFO - pulnest_app - get_wallet_balance - Line 38 - Get wallet balance for user 1.
2025-03-09 03:19:09,648 - INFO - pulnest_app - get_wallet_by_user_id - Line 33 - Wallet found for user 1.
2025-03-09 03:19:09,655 - INFO - pulnest_app - get_wallet_balance - Line 56 - Wallet balance retrieved for user 1.
2025-03-09 03:19:09,659 - ERROR - pulnest_app - get_wallet_balance - Line 50 - Error retrieving wallet balance for user 1: 404: Wallet not found
2025-03-09 03:23:30,071 - INFO - pulnest_app - get_wallet_balance - Line 38 - Get wallet balance for user 1.
2025-03-09 03:23:30,081 - INFO - pulnest_app - get_wallet_by_user_id - Line 30 - Wallet found for user 1.
2025-03-09 03:23:30,081 - INFO - pulnest_app - get_wallet_by_user_id - Line 31 - Mistake 1.
2025-03-09 03:23:30,081 - INFO - pulnest_app - get_wallet_balance - Line 56 - Wallet balance retrieved for user 1.
2025-03-09 03:23:30,081 - ERROR - pulnest_app - get_wallet_balance - Line 50 - Error retrieving wallet balance for user 1: 404: Wallet not found
2025-03-09 03:25:08,349 - INFO - pulnest_app - get_wallet_balance - Line 38 - Get wallet balance for user 1.
2025-03-09 03:25:08,361 - INFO - pulnest_app - get_wallet_by_user_id - Line 30 - Wallet found for user 1.
2025-03-09 03:25:08,363 - INFO - pulnest_app - get_wallet_balance - Line 56 - Wallet balance retrieved for user 1.
2025-03-09 03:25:08,363 - ERROR - pulnest_app - get_wallet_balance - Line 50 - Error retrieving wallet balance for user 1: 404: Wallet not found
2025-03-09 03:26:11,657 - INFO - pulnest_app - get_wallet_balance - Line 38 - Get wallet balance for user 1.
2025-03-09 03:26:11,665 - INFO - pulnest_app - get_wallet_by_user_id - Line 30 - Wallet found for user 1.
2025-03-09 03:26:11,665 - INFO - pulnest_app - get_wallet_balance - Line 56 - Wallet balance retrieved for user 1.
2025-03-09 03:26:11,665 - ERROR - pulnest_app - get_wallet_balance - Line 50 - Error retrieving wallet balance for user 1: 404: Wallet not found
2025-03-09 03:27:38,839 - INFO - pulnest_app - get_wallet_balance - Line 38 - Get wallet balance for user 1.
2025-03-09 03:27:38,848 - INFO - pulnest_app - get_wallet_by_user_id - Line 30 - Wallet found for user 1.
2025-03-09 03:27:38,853 - INFO - pulnest_app - get_wallet_balance - Line 56 - Wallet balance retrieved for user 1.
2025-03-09 03:28:32,381 - INFO - pulnest_app - get_wallet - Line 16 - Get wallet for user 1.
2025-03-09 03:28:32,381 - INFO - pulnest_app - get_wallet_by_user_id - Line 30 - Wallet found for user 1.
2025-03-09 03:28:32,381 - INFO - pulnest_app - get_wallet - Line 13 - Wallet retrieved for user 1.
2025-03-09 04:16:52,285 - INFO - pulnest_app - get_services_by_category_id - Line 97 - Retrieved 1 services for category 1.
2025-03-09 04:16:52,286 - ERROR - pulnest_app - get_services_by_category_id - Line 20 - Error retrieving services for category 1: Object of type Service is not JSON serializable
2025-03-09 04:24:57,427 - INFO - pulnest_app - get_services_by_category_id - Line 97 - Retrieved 1 services for category 1.
2025-03-09 18:25:16,149 - INFO - pulnest_app - get_services_by_category_id - Line 90 - Retrieved 1 services for category 1.
2025-03-09 18:25:16,149 - ERROR - pulnest_app - get_services_by_category_id - Line 156 - Error retrieving services for category 1: Object of type ServiceSchema is not JSON serializable
2025-03-09 18:28:24,578 - ERROR - pulnest_app - create_service - Line 20 - Error creating service for merchant Test: create_service() missing 1 required positional argument: 'category_id'
2025-03-09 18:28:24,578 - ERROR - pulnest_app - create_service - Line 23 - Error creating service: create_service() missing 1 required positional argument: 'category_id'
2025-03-09 18:30:43,041 - ERROR - pulnest_app - create_service - Line 20 - Error creating service for merchant Test: create_service() missing 1 required positional argument: 'category_id'
2025-03-09 18:30:43,041 - ERROR - pulnest_app - create_service - Line 23 - Error creating service: create_service() missing 1 required positional argument: 'category_id'
2025-03-09 21:37:03,019 - ERROR - pulnest_app - create_service - Line 20 - Error creating service for merchant Test: create_service() missing 1 required positional argument: 'category_id'
2025-03-09 21:37:03,019 - ERROR - pulnest_app - create_service - Line 23 - Error creating service: create_service() missing 1 required positional argument: 'category_id'
2025-03-09 21:40:29,967 - ERROR - pulnest_app - create_service - Line 17 - Error creating service for merchant Test: create_service() missing 1 required positional argument: 'category_id' here is the mistake
2025-03-09 21:40:29,967 - ERROR - pulnest_app - create_service - Line 23 - Error creating service: create_service() missing 1 required positional argument: 'category_id'
2025-03-09 21:44:00,139 - ERROR - pulnest_app - create_service - Line 18 - Error creating service for merchant Test: create_service() missing 1 required positional argument: 'category_id' here is the mistake
2025-03-09 21:44:00,139 - ERROR - pulnest_app - create_service - Line 23 - Error creating service: create_service() missing 1 required positional argument: 'category_id'
2025-03-09 21:46:20,894 - ERROR - pulnest_app - create_service - Line 18 - Error creating service for merchant Test: create_service() missing 1 required positional argument: 'category_id' here is the mistake
2025-03-09 21:46:20,894 - ERROR - pulnest_app - create_service - Line 23 - Error creating service: create_service() missing 1 required positional argument: 'category_id'
2025-03-09 21:46:36,447 - ERROR - pulnest_app - create_service - Line 18 - Error creating service for merchant Test: create_service() missing 1 required positional argument: 'category_id' here is the mistake
2025-03-09 21:46:36,447 - ERROR - pulnest_app - create_service - Line 24 - Error creating service: create_service() missing 1 required positional argument: 'category_id'
2025-03-09 21:49:11,555 - INFO - pulnest_app - create_service - Line 21 - Service created for merchant Test in DB.
2025-03-09 21:49:11,556 - ERROR - pulnest_app - create_service - Line 23 - Error creating service: Object of type set is not JSON serializable
2025-03-09 21:55:54,593 - INFO - pulnest_app - create_service - Line 21 - Service created for merchant Test in DB.
2025-03-09 21:58:26,341 - WARNING - pulnest_app - get_service_by_id - Line 37 - No service found with ID 2 in DB.
2025-03-09 21:58:26,346 - ERROR - pulnest_app - get_service_by_id - Line 50 - Error retrieving service 2: 404: Service not found
2025-03-09 21:58:54,248 - INFO - pulnest_app - get_service_by_id - Line 34 - Service 4 retrieved from DB.
2025-03-09 21:58:54,249 - ERROR - pulnest_app - get_service_by_id - Line 50 - Error retrieving service 4: Object of type ServiceSchema is not JSON serializable
2025-03-09 22:12:25,213 - INFO - pulnest_app - get_service_by_id - Line 34 - Service 4 retrieved from DB.
2025-03-09 22:12:25,215 - ERROR - pulnest_app - get_service_by_id - Line 52 - Error retrieving service 4: 'ServiceSchema' object has no attribute 'model_dump'
2025-03-09 22:15:01,179 - INFO - pulnest_app - get_service_by_id - Line 34 - Service 4 retrieved from DB.
2025-03-09 22:16:24,658 - WARNING - pulnest_app - get_service_by_id - Line 37 - No service found with ID 1 in DB.
2025-03-09 22:16:24,658 - ERROR - pulnest_app - get_service_by_id - Line 52 - Error retrieving service 1: 404: Service not found
2025-03-09 22:18:02,679 - WARNING - pulnest_app - get_service_by_id - Line 37 - No service found with ID 1 in DB.
2025-03-09 22:18:02,680 - ERROR - pulnest_app - get_service_by_id - Line 52 - Error retrieving service 1: 404: Service not found
2025-03-09 22:21:31,144 - WARNING - pulnest_app - get_service_by_id - Line 37 - No service found with ID 1 in DB.
2025-03-09 22:21:31,145 - ERROR - pulnest_app - get_service_by_id - Line 51 - Error retrieving service 1: __init__() got an unexpected keyword argument 'detail'
2025-03-09 22:23:07,708 - WARNING - pulnest_app - get_service_by_id - Line 37 - No service found with ID 1 in DB.
2025-03-09 22:23:10,661 - INFO - pulnest_app - get_service_by_id - Line 34 - Service 4 retrieved from DB.
2025-03-09 22:29:35,454 - INFO - pulnest_app - get_services_by_category_id - Line 84 - Retrieved 3 services for category 1.
2025-03-09 22:29:35,457 - ERROR - pulnest_app - get_services_by_category_id - Line 156 - Error retrieving services for category 1: Object of type ServiceSchema is not JSON serializable
2025-03-09 22:30:32,320 - WARNING - pulnest_app - get_service_by_merchant_name - Line 52 - No service found for merchant "Test" in DB.
2025-03-09 22:30:32,321 - ERROR - pulnest_app - get_service_by_merchant_name - Line 80 - Error retrieving service for merchant "Test": 404: Service not found
2025-03-10 11:24:05,417 - INFO - pulnest_app - create_service - Line 21 - Service created for merchant Test 2 in DB.
2025-03-10 11:24:10,100 - INFO - pulnest_app - get_service_by_id - Line 34 - Service 4 retrieved from DB.
2025-03-10 11:24:15,028 - WARNING - pulnest_app - get_service_by_id - Line 37 - No service found with ID 1 in DB.
2025-03-10 11:24:17,958 - INFO - pulnest_app - get_service_by_id - Line 34 - Service 5 retrieved from DB.
2025-03-10 11:24:21,488 - INFO - pulnest_app - get_service_by_id - Line 34 - Service 6 retrieved from DB.
2025-03-10 11:24:24,876 - INFO - pulnest_app - get_service_by_id - Line 34 - Service 7 retrieved from DB.
2025-03-10 11:24:30,754 - WARNING - pulnest_app - get_service_by_merchant_name - Line 52 - No service found for merchant "Test" in DB.
2025-03-10 11:24:30,756 - ERROR - pulnest_app - get_service_by_merchant_name - Line 80 - Error retrieving service for merchant "Test": 404: Service not found
2025-03-10 11:26:37,816 - WARNING - pulnest_app - get_service_by_merchant_name - Line 52 - No service found for merchant "Test" in DB.
2025-03-10 11:33:16,992 - WARNING - pulnest_app - get_service_by_merchant_name - Line 52 - No service found for merchant "Test" in DB.
2025-03-10 11:33:55,380 - WARNING - pulnest_app - get_service_by_merchant_name - Line 52 - No service found for merchant "Test" in DB.
2025-03-10 11:33:57,910 - WARNING - pulnest_app - get_service_by_merchant_name - Line 52 - No service found for merchant "Test" in DB.
2025-03-10 11:33:59,643 - WARNING - pulnest_app - get_service_by_merchant_name - Line 52 - No service found for merchant "Test" in DB.
2025-03-10 11:38:35,127 - INFO - pulnest_app - get_service_by_merchant_name - Line 48 - Query result: None
2025-03-10 11:38:35,128 - WARNING - pulnest_app - get_service_by_merchant_name - Line 53 - No service found for merchant "Test" in DB.
2025-03-10 11:38:55,491 - INFO - pulnest_app - get_service_by_merchant_name - Line 48 - Query result: None
2025-03-10 11:38:55,492 - WARNING - pulnest_app - get_service_by_merchant_name - Line 53 - No service found for merchant "Test" in DB.
2025-03-10 11:40:01,407 - INFO - pulnest_app - get_service_by_merchant_name - Line 48 - Query result: None
2025-03-10 11:40:01,407 - WARNING - pulnest_app - get_service_by_merchant_name - Line 53 - No service found for merchant "Test" in DB.
2025-03-10 11:40:42,629 - INFO - pulnest_app - get_service_by_merchant_name - Line 62 - Endpoint result: "Test"
2025-03-10 11:40:42,640 - INFO - pulnest_app - get_service_by_merchant_name - Line 48 - Query result: None
2025-03-10 11:40:42,641 - WARNING - pulnest_app - get_service_by_merchant_name - Line 53 - No service found for merchant "Test" in DB.
2025-03-10 11:44:36,793 - INFO - pulnest_app - get_service_by_merchant_name - Line 62 - Endpoint result: "Test"
2025-03-10 11:44:36,802 - INFO - pulnest_app - get_service_by_merchant_name - Line 50 - Query result: None
2025-03-10 11:44:36,811 - WARNING - pulnest_app - get_service_by_merchant_name - Line 55 - No service found for merchant "Test" in DB.
2025-03-10 11:45:36,119 - INFO - pulnest_app - get_service_by_merchant_name - Line 62 - Endpoint result: "Test 2"
2025-03-10 11:45:36,121 - INFO - pulnest_app - get_service_by_merchant_name - Line 50 - Query result: None
2025-03-10 11:45:36,123 - WARNING - pulnest_app - get_service_by_merchant_name - Line 55 - No service found for merchant "Test 2" in DB.
2025-03-10 11:46:23,489 - INFO - pulnest_app - get_service_by_merchant_name - Line 62 - Endpoint result: "Test 2"
2025-03-10 11:46:23,489 - INFO - pulnest_app - get_service_by_merchant_name - Line 49 - Querying for merchant: "Test 2"
2025-03-10 11:46:23,502 - INFO - pulnest_app - get_service_by_merchant_name - Line 52 - Query result: None
2025-03-10 11:46:23,506 - WARNING - pulnest_app - get_service_by_merchant_name - Line 57 - No service found for merchant "Test 2" in DB.
2025-03-10 11:47:54,762 - INFO - pulnest_app - get_services_by_category_id - Line 84 - Retrieved 3 services for category 1.
2025-03-10 11:47:54,762 - ERROR - pulnest_app - get_services_by_category_id - Line 159 - Error retrieving services for category 1: Object of type ServiceSchema is not JSON serializable
2025-03-10 11:49:01,980 - INFO - pulnest_app - get_all_services - Line 45 - Retrieved 4 services.
2025-03-10 11:49:01,980 - ERROR - pulnest_app - get_all_services - Line 109 - Error retrieving all services: Object of type ServiceSchema is not JSON serializable
2025-03-10 11:51:06,554 - INFO - pulnest_app - get_all_services - Line 45 - Retrieved 4 services.
2025-03-10 11:51:56,565 - INFO - pulnest_app - get_all_services - Line 45 - Retrieved 4 services.
2025-03-10 11:52:06,115 - INFO - pulnest_app - get_service_by_merchant_name - Line 62 - Endpoint result: "Test 2"
2025-03-10 11:52:06,115 - INFO - pulnest_app - get_service_by_merchant_name - Line 49 - Querying for merchant: "Test 2"
2025-03-10 11:52:06,130 - INFO - pulnest_app - get_service_by_merchant_name - Line 52 - Query result: None
2025-03-10 11:52:06,130 - WARNING - pulnest_app - get_service_by_merchant_name - Line 57 - No service found for merchant "Test 2" in DB.
2025-03-10 11:56:29,934 - INFO - pulnest_app - get_services_by_category_id - Line 84 - Retrieved 3 services for category 1.
2025-03-10 11:58:15,392 - INFO - pulnest_app - get_services_by_category_id - Line 84 - Retrieved 3 services for category 1.
2025-03-10 11:58:18,195 - INFO - pulnest_app - get_services_by_category_id - Line 84 - Retrieved 1 services for category 2.
2025-03-10 11:58:20,918 - INFO - pulnest_app - get_services_by_category_id - Line 84 - Retrieved 0 services for category 3.
2025-03-10 12:03:33,592 - INFO - pulnest_app - update_service - Line 97 - Service 5 updated.
2025-03-10 12:03:33,593 - INFO - pulnest_app - deactivate_service - Line 56 - Service 5 deactivated.
2025-03-10 12:03:33,594 - ERROR - pulnest_app - deactivate_service - Line 169 - Error deactivating service 5: Instance <Service at 0x1f442760760> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
2025-03-10 12:07:52,219 - WARNING - pulnest_app - update_service - Line 99 - No service found with ID 5 in DB.
2025-03-10 12:09:31,266 - WARNING - pulnest_app - update_service - Line 99 - No service found with ID 5 in DB.
2025-03-10 12:09:35,280 - WARNING - pulnest_app - update_service - Line 99 - No service found with ID 2 in DB.
2025-03-10 12:10:39,340 - WARNING - pulnest_app - update_service - Line 99 - No service found with ID 2 in DB.
2025-03-10 12:10:48,472 - INFO - pulnest_app - update_service - Line 96 - Service 4 updated.
2025-03-10 12:10:48,473 - INFO - pulnest_app - deactivate_service - Line 56 - Service 4 deactivated.
2025-03-10 12:10:48,473 - ERROR - pulnest_app - deactivate_service - Line 169 - Error deactivating service 4: Instance <Service at 0x26818bdf640> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
2025-03-10 12:16:30,314 - WARNING - pulnest_app - update_service - Line 105 - No service found with ID 4 in DB.
2025-03-10 12:17:03,858 - INFO - pulnest_app - update_service - Line 90 - Service instance in session: True
2025-03-10 12:17:03,861 - INFO - pulnest_app - update_service - Line 102 - Service 4 updated.
2025-03-10 12:17:03,862 - INFO - pulnest_app - deactivate_service - Line 56 - Service 4 deactivated.
2025-03-10 12:17:03,864 - ERROR - pulnest_app - deactivate_service - Line 169 - Error deactivating service 4: Instance <Service at 0x21e6bb2f610> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
2025-03-10 12:19:20,180 - WARNING - pulnest_app - soft_delete_service - Line 123 - No service found with ID 2 in DB.
2025-03-10 12:19:20,180 - ERROR - pulnest_app - soft_delete_service - Line 192 - Error soft deleting service 2: 404: Service not found
2025-03-10 12:22:25,672 - INFO - pulnest_app - update_service - Line 90 - Service instance in session: True
2025-03-10 12:22:25,684 - INFO - pulnest_app - update_service - Line 102 - Service 4 updated.
2025-03-10 12:22:25,684 - INFO - pulnest_app - deactivate_service - Line 56 - Service 4 deactivated.
2025-03-10 12:22:25,685 - ERROR - pulnest_app - deactivate_service - Line 169 - Error deactivating service 4: Instance <Service at 0x14e10e99eb0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
2025-03-10 12:24:04,606 - WARNING - pulnest_app - update_service - Line 103 - No service found with ID 4 in DB.
2025-03-10 12:24:20,478 - INFO - pulnest_app - update_service - Line 90 - Service instance in session: True
2025-03-10 12:24:20,491 - INFO - pulnest_app - update_service - Line 100 - Service 6 updated.
2025-03-10 12:24:20,493 - INFO - pulnest_app - deactivate_service - Line 56 - Service 6 deactivated.
2025-03-10 12:24:20,494 - ERROR - pulnest_app - deactivate_service - Line 169 - Error deactivating service 6: 'int' object has no attribute 'merchant_name'
2025-03-10 12:26:08,758 - INFO - pulnest_app - update_service - Line 90 - Service instance in session: True
2025-03-10 12:26:08,773 - INFO - pulnest_app - update_service - Line 100 - Service 6 updated.
2025-03-10 12:26:08,776 - INFO - pulnest_app - deactivate_service - Line 56 - Service 6 deactivated.
2025-03-10 12:26:08,776 - ERROR - pulnest_app - deactivate_service - Line 169 - Error deactivating service 6: Object of type set is not JSON serializable
2025-03-10 12:26:43,136 - WARNING - pulnest_app - update_service - Line 103 - No service found with ID 6 in DB.
2025-03-10 12:26:46,904 - INFO - pulnest_app - update_service - Line 90 - Service instance in session: True
2025-03-10 12:26:46,917 - INFO - pulnest_app - update_service - Line 100 - Service 4 updated.
2025-03-10 12:26:46,920 - INFO - pulnest_app - deactivate_service - Line 56 - Service 4 deactivated.
2025-03-10 12:26:46,920 - ERROR - pulnest_app - deactivate_service - Line 169 - Error deactivating service 4: Object of type set is not JSON serializable
2025-03-10 12:27:53,355 - WARNING - pulnest_app - update_service - Line 103 - No service found with ID 4 in DB.
2025-03-10 12:28:09,134 - INFO - pulnest_app - update_service - Line 90 - Service instance in session: True
2025-03-10 12:28:09,154 - INFO - pulnest_app - update_service - Line 100 - Service 5 updated.
2025-03-10 12:28:09,157 - INFO - pulnest_app - deactivate_service - Line 56 - Service 5 deactivated.
2025-03-10 12:28:09,157 - ERROR - pulnest_app - deactivate_service - Line 169 - Error deactivating service 5: 'str' object has no attribute 'dict'
2025-03-10 12:29:29,008 - INFO - pulnest_app - update_service - Line 90 - Service instance in session: True
2025-03-10 12:29:29,024 - INFO - pulnest_app - update_service - Line 100 - Service 7 updated.
2025-03-10 12:29:29,024 - INFO - pulnest_app - deactivate_service - Line 56 - Service 7 deactivated.
2025-03-10 12:29:29,040 - ERROR - pulnest_app - deactivate_service - Line 169 - Error deactivating service 7: Object of type set is not JSON serializable
2025-03-10 12:30:52,225 - WARNING - pulnest_app - update_service - Line 103 - No service found with ID 7 in DB.
2025-03-10 12:31:08,187 - INFO - pulnest_app - update_service - Line 90 - Service instance in session: True
2025-03-10 12:31:08,200 - INFO - pulnest_app - update_service - Line 100 - Service 4 updated.
2025-03-10 12:31:08,202 - INFO - pulnest_app - deactivate_service - Line 56 - Service 4 deactivated.
2025-03-10 12:31:16,137 - WARNING - pulnest_app - update_service - Line 103 - No service found with ID 7 in DB.
2025-03-10 12:32:40,285 - WARNING - pulnest_app - update_service - Line 103 - No service found with ID 7 in DB.
2025-03-10 12:32:57,387 - WARNING - pulnest_app - update_service - Line 103 - No service found with ID 1 in DB.
2025-03-10 12:33:00,825 - WARNING - pulnest_app - update_service - Line 103 - No service found with ID 1 in DB.
2025-03-10 12:34:13,268 - WARNING - pulnest_app - update_service - Line 103 - No service found with ID 1 in DB.
2025-03-10 12:40:44,474 - WARNING - pulnest_app - soft_delete_service - Line 121 - No service found with ID 2 in DB.
2025-03-10 12:40:44,475 - ERROR - pulnest_app - soft_delete_service - Line 192 - Error soft deleting service 2: 404: Service not found
2025-03-10 12:41:15,186 - WARNING - pulnest_app - soft_delete_service - Line 121 - No service found with ID 2 in DB.
2025-03-10 12:41:25,084 - INFO - pulnest_app - soft_delete_service - Line 118 - Service 6 soft deleted in DB.
2025-03-10 12:41:25,084 - INFO - pulnest_app - soft_delete_service - Line 95 - Service 6 soft deleted.
2025-03-10 12:41:25,084 - ERROR - pulnest_app - soft_delete_service - Line 192 - Error soft deleting service 6: Instance <Service at 0x124a191f370> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
2025-03-10 12:44:33,590 - INFO - pulnest_app - soft_delete_service - Line 118 - Service 4 soft deleted in DB.
2025-03-10 12:44:33,593 - INFO - pulnest_app - soft_delete_service - Line 95 - Service 4 soft deleted.
2025-03-10 12:44:33,593 - ERROR - pulnest_app - soft_delete_service - Line 192 - Error soft deleting service 4: 'int' object has no attribute 'merchant_name'
2025-03-10 12:45:01,172 - WARNING - pulnest_app - soft_delete_service - Line 121 - No service found with ID 4 in DB.
2025-03-10 12:45:11,610 - INFO - pulnest_app - soft_delete_service - Line 118 - Service 5 soft deleted in DB.
2025-03-10 12:45:11,614 - INFO - pulnest_app - soft_delete_service - Line 95 - Service 5 soft deleted.
2025-03-10 12:45:11,615 - ERROR - pulnest_app - soft_delete_service - Line 192 - Error soft deleting service 5: Object of type set is not JSON serializable
2025-03-10 12:46:12,292 - INFO - pulnest_app - soft_delete_service - Line 118 - Service 4 soft deleted in DB.
2025-03-10 12:46:12,294 - INFO - pulnest_app - soft_delete_service - Line 95 - Service 4 soft deleted.
2025-03-10 12:46:22,067 - WARNING - pulnest_app - soft_delete_service - Line 121 - No service found with ID 5 in DB.
2025-03-10 12:46:32,612 - INFO - pulnest_app - get_service_by_merchant_name - Line 62 - Endpoint result: "Test"
2025-03-10 12:46:32,612 - INFO - pulnest_app - get_service_by_merchant_name - Line 49 - Querying for merchant: "Test"
2025-03-10 12:46:32,614 - INFO - pulnest_app - get_service_by_merchant_name - Line 52 - Query result: None
2025-03-10 12:46:32,615 - WARNING - pulnest_app - get_service_by_merchant_name - Line 57 - No service found for merchant "Test" in DB.
2025-03-10 12:46:36,931 - INFO - pulnest_app - get_service_by_merchant_name - Line 62 - Endpoint result: Test
2025-03-10 12:46:36,931 - INFO - pulnest_app - get_service_by_merchant_name - Line 49 - Querying for merchant: Test
2025-03-10 12:46:36,933 - INFO - pulnest_app - get_service_by_merchant_name - Line 52 - Query result: None
2025-03-10 12:46:36,933 - WARNING - pulnest_app - get_service_by_merchant_name - Line 57 - No service found for merchant Test in DB.
2025-03-10 12:46:39,342 - INFO - pulnest_app - get_service_by_merchant_name - Line 62 - Endpoint result: Test
2025-03-10 12:46:39,343 - INFO - pulnest_app - get_service_by_merchant_name - Line 49 - Querying for merchant: Test
2025-03-10 12:46:39,345 - INFO - pulnest_app - get_service_by_merchant_name - Line 52 - Query result: None
2025-03-10 12:46:39,345 - WARNING - pulnest_app - get_service_by_merchant_name - Line 57 - No service found for merchant Test in DB.
2025-03-10 12:48:56,944 - INFO - pulnest_app - get_service_by_merchant_name - Line 62 - Endpoint result: Test
2025-03-10 12:48:56,945 - INFO - pulnest_app - get_service_by_merchant_name - Line 49 - Querying for merchant: Test
2025-03-10 12:48:56,946 - INFO - pulnest_app - get_service_by_merchant_name - Line 52 - Query result: <db.models.Service object at 0x0000021A13929E80>
2025-03-10 12:48:56,947 - INFO - pulnest_app - get_service_by_merchant_name - Line 54 - Service found for merchant Test in DB.
2025-03-10 12:48:56,947 - ERROR - pulnest_app - get_service_by_merchant_name - Line 83 - Error retrieving service for merchant Test: Object of type ServiceResponse is not JSON serializable
2025-03-10 12:49:50,178 - INFO - pulnest_app - get_service_by_merchant_name - Line 49 - Querying for merchant: Test
2025-03-10 12:49:50,190 - INFO - pulnest_app - get_service_by_merchant_name - Line 52 - Query result: <db.models.Service object at 0x000001A891EFBE20>
2025-03-10 12:49:50,190 - INFO - pulnest_app - get_service_by_merchant_name - Line 54 - Service found for merchant Test in DB.
2025-03-10 12:50:10,020 - INFO - pulnest_app - get_service_by_merchant_name - Line 49 - Querying for merchant: Test 1
2025-03-10 12:50:10,022 - INFO - pulnest_app - get_service_by_merchant_name - Line 52 - Query result: None
2025-03-10 12:50:10,023 - WARNING - pulnest_app - get_service_by_merchant_name - Line 57 - No service found for merchant Test 1 in DB.
2025-03-10 12:50:16,149 - INFO - pulnest_app - get_service_by_merchant_name - Line 49 - Querying for merchant: Testing
2025-03-10 12:50:16,151 - INFO - pulnest_app - get_service_by_merchant_name - Line 52 - Query result: None
2025-03-10 12:50:16,152 - WARNING - pulnest_app - get_service_by_merchant_name - Line 57 - No service found for merchant Testing in DB.
2025-03-10 12:50:41,579 - INFO - pulnest_app - get_service_by_merchant_name - Line 49 - Querying for merchant: Testing
2025-03-10 12:50:41,584 - INFO - pulnest_app - get_service_by_merchant_name - Line 52 - Query result: None
2025-03-10 12:50:41,585 - WARNING - pulnest_app - get_service_by_merchant_name - Line 57 - No service found for merchant Testing in DB.
2025-03-10 12:50:49,124 - INFO - pulnest_app - get_service_by_merchant_name - Line 49 - Querying for merchant: Test 2
2025-03-10 12:50:49,126 - INFO - pulnest_app - get_service_by_merchant_name - Line 52 - Query result: None
2025-03-10 12:50:49,126 - WARNING - pulnest_app - get_service_by_merchant_name - Line 57 - No service found for merchant Test 2 in DB.
2025-03-10 12:50:52,581 - INFO - pulnest_app - get_service_by_merchant_name - Line 49 - Querying for merchant: Tests
2025-03-10 12:50:52,583 - INFO - pulnest_app - get_service_by_merchant_name - Line 52 - Query result: <db.models.Service object at 0x000001A891F73430>
2025-03-10 12:50:52,583 - INFO - pulnest_app - get_service_by_merchant_name - Line 54 - Service found for merchant Tests in DB.
2025-03-10 12:51:06,588 - INFO - pulnest_app - get_service_by_merchant_name - Line 49 - Querying for merchant: Test 2
2025-03-10 12:51:06,592 - INFO - pulnest_app - get_service_by_merchant_name - Line 52 - Query result: <db.models.Service object at 0x000001A891F73AF0>
2025-03-10 12:51:06,593 - INFO - pulnest_app - get_service_by_merchant_name - Line 54 - Service found for merchant Test 2 in DB.
